### ISSUE TITLE
ERROR: keras-rl2 1.0.3 has requirement tensorflow==2.0.0-beta1, but you'll have tensorflow 2.1.0 which is incompatible. 

### ISSUE THREAD

**Issue by Valdas-Stonkus** [wau/keras-rl2#19]
Hello, 

requirement for keras-rl2 is tensorflow ==2.1.0
When I installed keras-rl2 by pip, it removed my tensorflow 2.1.0 and instaled 2.0.0beta version.

But my code did nor ran and I tryed install tensorflow 2.1.0 as it requires, but got this error
"ERROR: keras-rl2 1.0.3 has requirement tensorflow==2.0.0-beta1, but you'll have tensorflow 2.1.0 which is incompatible.
Installing collected packages: tensorflow
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.0.0b1
    Uninstalling tensorflow-2.0.0b1:
      Successfully uninstalled tensorflow-2.0.0b1
Successfully installed tensorflow-2.1.0"

- [ X] Check that you are up-to-date with the master branch of Keras-RL. You can update with:
`pip install git+git://github.com/wau/keras-rl2.git --upgrade --no-deps`

- [ X] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps`

**Comment by inarikami** [comment]
The pypi wheels have been updated with the latest changes in the github branch.
Running 
```shell
pip install keras-rl2
```
now installs keras-rl2 with the latest 2.1.0 tensorflow version.
