### ISSUE TITLE
TypeError: len is not well defined for symbolic Tensors. (activation_4/Identity:0) Please call `x.shape` rather than `len(x)` for shape information.

### ISSUE THREAD

**Issue by jeffheaton** [wau/keras-rl2#4]
Running latest Keras-RL and nightly TensorFlow 2.0 (tf-nightly-2.0-preview), I get the following error trying to run:

https://github.com/wau/keras-rl2/blob/master/examples/dqn_atari.py

I get the following error.  Running Python 3.6 (Anaconda):

```
2019-08-08 17:55:57.294275: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-08 17:55:57.312932: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fbb2e93a0a0 executing computations on platform Host. Devices:
2019-08-08 17:55:57.312954: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
permute (Permute)            (None, 84, 84, 4)         0         
_________________________________________________________________
conv2d (Conv2D)              (None, 20, 20, 32)        8224      
_________________________________________________________________
activation (Activation)      (None, 20, 20, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 9, 9, 64)          32832     
_________________________________________________________________
activation_1 (Activation)    (None, 9, 9, 64)          0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 7, 7, 64)          36928     
_________________________________________________________________
activation_2 (Activation)    (None, 7, 7, 64)          0         
_________________________________________________________________
flatten (Flatten)            (None, 3136)              0         
_________________________________________________________________
dense (Dense)                (None, 512)               1606144   
_________________________________________________________________
activation_3 (Activation)    (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 2052      
_________________________________________________________________
activation_4 (Activation)    (None, 4)                 0         
=================================================================
Total params: 1,686,180
Trainable params: 1,686,180
Non-trainable params: 0
_________________________________________________________________
None
Traceback (most recent call last):
  File "atari2.py", line 96, in <module>
    train_interval=4, delta_clip=1.)
  File "/Users/jheaton/.local/lib/python3.6/site-packages/rl/agents/dqn.py", line 107, in __init__
    if hasattr(model.output, '__len__') and len(model.output) > 1:
  File "/Users/jheaton/miniconda3/envs/tensorflow2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 738, in __len__
    "shape information.".format(self.name))
TypeError: len is not well defined for symbolic Tensors. (activation_4/Identity:0) Please call `x.shape` rather than `len(x)` for shape information.
```

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question in the [Discord](https://discord.gg/FfRgSU).

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras-RL. You can update with:
`pip install git+git://github.com/wau/keras-rl2.git --upgrade --no-deps`

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps`

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short). If you report an error, please include the error message and the backtrace.

**Comment by inarikami** [comment]
https://github.com/wau/keras-rl2/commit/70232f449e35abb756f22912be4fea78c9fb5f58 The pypi package has been updated to require the installation of tensorflow 2.0.0 beta 1. This fixes the ```len is not well defined for symbolic Tensors``` error.

**Comment by jeffheaton** [comment]
Thanks, that fixes it.  Should you also update the README.md to suggest installing beta1, rather than the nightly (like it currently suggests)?

**Comment by inarikami** [comment]
Updated the readme too 😄

**Comment by kingxiaotian** [comment]
how to solve this TypeError?

**Comment by inarikami** [comment]
@kingxiaotian you will need to use the beta version of tensorflow 2.0.0 which can be downloaded using > pip install tensorflow==2.0.0-beta

**Comment by vincenzodentamaro** [comment]
Thank you old friend @jeffheaton it's a pleasure to see we all get same errors ;)

**Comment by palbha** [comment]
Hi all , I have followed to above steps still facing the same issue , any more suggestion on the same will be appreciated .

**Comment by cossio** [comment]
I am getting this error now!

**Comment by edurenye** [comment]
My PR fixes this error: #9

**Comment by bigboy32** [comment]
I have tensorflow-gpu 2.1.0 do i need to downgrade?

**Comment by ladychili** [comment]
> @kingxiaotian you will need to use the beta version of tensorflow 2.0.0 which can be downloaded using > pip install tensorflow==2.0.0-beta

I installed 2.0.0-beta, still getting this error though. Any ideas?

**Comment by indhra** [comment]
> pip install tensorflow==2.0.0-beta

worked out for me 
thanks

**Comment by jaroslav87** [comment]
> I have tensorflow-gpu 2.1.0 do i need to downgrade?

Good question! I'm getting the same error with tensorflow 2.1.0

**Comment by inarikami** [comment]
@jaroslav87 the latest keras-rl2 pypi binaries now include support for tensorflow 2.1.0 👍

**Comment by ljstrnadiii** [comment]
I am getting the same issue with 

```
def add_noise(image):
    # sample inputs
    var = tf.random.uniform((1,), 1, 5)
    kernel_size = tf.random.uniform((1,), 5, 30)
    
    # gen noise and clip
    n_im = tf.random.normal((1, 100, 100, 3), 0, var)
    n_im = tf.clip_by_value(n_im, 0, 1)
    
    # pool noise
    n_im = tf.nn.avg_pool2d(n_im, kernel_size, 1, 'SAME') 
    n_im = tf.squeeze(n_im, axis=0)
    
    return image + noise

# fake dataset
dset = tf.data.Dataset.from_tensor_slices(
    np.zeros((10,100,100,3))
)

# add noise
dset = dset.map(add_noise)
```

Any ideas how to fix or am I just doing this all wrong? I am on the latest build using docker.

**Comment by jaroslav87** [comment]
@ljstrnadiii error that you get is replicable, it is most likely caused by n_im = tf.nn.avg_pool2d(n_im, kernel_size, 1, 'SAME') . I tried to replace it by n_im = tf.keras.backend.pool2d(n_im, kernel_size, strides=(1, 1),  pool_mode='avg') but got the same error

**Comment by ljstrnadiii** [comment]
@jaroslav87 , yeah, if I instead hardcode the kernel_size with 10 for example instead of sampling for the value, no issue.
